zuul:
  routes:
    reports-api:
      sensitiveHeaders: Cookie,Set-Cookie
      path: /api/**
      url: http://${REPORTS_API_SERVICE_HOST}:${REPORTS_API_SERVICE_PORT}/reports-api

jmx-ui:
  amv-data-api-password: 6AKRgu0wLPQP28Qhn9QQK7m69B1XrM/PqEMMPZTqZFll8/5wT36FIW5LXCZherYT
  app-base-url: https://amvprod.amvholdings.com/jmx-ui
