zuul:
  routes:
    reports-api:
      sensitiveHeaders: Cookie,Set-Cookie
      path: /api/**
      url: http://${AMV_DATA_API_SERVICE_HOST}:${AMV_DATA_API_SERVICE_PORT}/reports-api

jmx-ui:
  amv-data-api-password: pYP8pydhqRWcGJwXWfmRlmgMNN+nPVSrqCRgU2gidDaWNpOo5J7KKZxKOgxgUYK/

